spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/nutriscanner
spring.datasource.username=postgres
spring.datasource.password=eya
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
groq.api.key={GROQ_API_KEY}
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false
server.port=${PORT:8081}
